### ISSUE TITLE
generator models

### ISSUE THREAD

**Issue by bartengine27** [ravisvi/super-resolution-videos#2]
Hi,

  Thanks for sharing your work!

  How do I use the ..L1_1.npz and ..L1_2.npz generator models?

  The video output is rather dark, is this related to the brightness remark in your report? Should I change anything in the code?

Thanks!
Bart

**Comment by SubRighteous** [comment]
https://github.com/ravisvi/super-resolution-videos/blob/f70e9e8f2f092497f45f3e040475e1377feff4a8/video_super_resolver.py#L65

just change 'g_srgan.npz' to 'g_srgan_L1_1.npz' or 'g_srgan_L1_2.npz'

**Comment by ravisvi** [comment]
Hey Bart, 

Apologies for the late reply. I should really be answering this questions within a week instead of within a year. 

So both of those models are just different models with variation to the loss function. 
You just have to specify the model in video_super_resolver.py in line 65:
`tl.files.load_and_assign_npz(sess=sess, name=os.path.join(checkpoint_dir, 'g_srgan.npz'), network=net_g)`

Ravi
